[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
disabled = '!has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/vimshell.vim'
depends = 'vimproc.vim'
on_map = '<Plug>(vimshell_'
on_cmd = 'VimShell'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_i = 1
on_ft = 'snippet'

[[plugins]]
repo = 'ujihisa/neco-look'
on_i = 1

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = '<Plug>(vimfiler_'
on_path = '.*'

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = [['sxno', '<Plug>(easymotion-']]
on_func = ['EasyMotion#go', 'EasyMotion#User',
           'EasyMotion#JK', 'EasyMotion#is_active']

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = 'vimproc.vim'
on_map = '<Plug>(quickrun)'
on_cmd = 'QuickRun'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
on_source = 'vim-quickrun'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
on_cmd = ['WatchdogsRun']

[[plugins]]
repo = 'osyo-manga/unite-quickfix'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/unite-filetype'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_map = '<Plug>(anzu-'

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = 'unite.vim'

[[plugins]]
repo = 'tyru/caw.vim'
on_map = '<Plug>(caw:'

[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = [['nx', '<Plug>(EasyAlign)']]

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_map = [['nx', '<Plug>(operator-replace)']]

[[plugins]]
repo = 'kana/vim-textobj-indent'
depends = 'vim-operator-user'
on_map = [['xo', 'ai'], ['xo', 'aI'], ['xo', 'ii'], ['xo', 'iI']]

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
on_map = [['nx', '<Plug>(operator-surround-']]

[[plugins]]
repo = 'rhysd/clever-f.vim'
on_map = [['sxno', '<Plug>(clever-f-']]

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown', 'rst', 'mkd']
depends = 'open-browser.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_cmd = ['PreVimOpen']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'

[[plugins]]
repo = 'mattn/excelview-vim'
on_cmd = ['ExcelView']
depends = 'webapi-vim'
