# [[plugins]]
# repo = 'Shougo/denite.nvim'
# if = 'v:version >= 800 && has("python3")'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/unite-quickfix'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/unite-filetype'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
disabled = '!has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_ft = 'snippet'
on_i = 1

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'
depends = 'vimproc.vim'
on_map = {n = '<Plug>'}
on_cmd = 'VimShell'

[[plugins]]
repo = 'cocopon/vaffle.vim'
on_map = {n = '<Plug>'}
on_cmd = 'Vaffle'

[[plugins]]
repo = 'ujihisa/neco-look'
on_source = ['neocomplete.vim']

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = {n = '<Plug>'}
on_func = ['EasyMotion#go']

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = 'vimproc.vim'
on_map = {n = '<Plug>'}
on_cmd = 'QuickRun'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
on_source = 'vim-quickrun'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_map = {n = '<Plug>'}

[[plugins]]
repo = 'tyru/caw.vim'
on_map = {nv = '<Plug>'}

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = 'UndotreeToggle'

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = {nx = '<Plug>'}

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_map = {nx = '<Plug>'}

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
on_map = {nx = '<Plug>'}

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = {nv = '<Plug>(openbrowser-'}
on_cmd = ['OpenBrowser', 'OpenBrowserSmartSearch']

[[plugins]]
repo = 'kannokanno/previm'
depends = 'open-browser.vim'
on_ft = ['markdown', 'rst', 'mkd']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'wavded/vim-stylus'
on_ft = 'stylus'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

